### ISSUE TITLE
document Expired

### ISSUE THREAD

**Issue by catsalty** [hawkingrei/g53#8]
put 过去显示的是404

**Comment by hawkingrei** [comment]
抱歉抱歉，我在大改restful，还没有开放使用
现在添加域名的话，
是这样的
curl http://<ip>:<port>/service -X PUT --data-ascii '{"RecordType":"A","Value":"192.168.5.63","TTL":3600,"Aliases":"www-t099.duitang.net"}'

**Comment by hawkingrei** [comment]
抱歉抱歉，我还没改动reademe，今天就把他更新了

**Comment by hawkingrei** [comment]
已经更新文档

**Comment by hawkingrei** [comment]
@byecode  还有什么问题吗？
